# Generated by Django 4.1.2 on 2022-10-22 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('public_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.SmallIntegerField(null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('price_after_discount', models.BigIntegerField(blank=True, null=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('public_time', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='product.category')),
            ],
        ),
    ]
